bicopter_angle_controller:
  ros__parameters:

    # node
    controller_rate: 240.0

    # subscriber topics
    angle_commands_topic: /bicopter/angle_commands
    actuator_commands_topic: /bicopter/actuator_commands
    sensor_readings_topic: /bicopter/sensor_readings

    # angle limits
    limits:
      roll: 0.2
      pitch: 0.2
      height: 5.0
      d_roll: 1.0
      d_pitch: 1.0
      d_yaw: 1.0
      d_height: 1.0

    # model properties for computing jacobian
    model_properties:
      package: bicopter_model
      file: urdf/bicopter_properties.yaml

    # controller
    gains:
      roll:
        kp: 300.0
        kd: 30.0
      pitch:
        kp: 700.0
        kd: 100.0
      yaw:
        kp: 100.0  # 0 means no yaw position control
        kd: 20.0
      height:
        kp: 10.0
        kd: 5.0



